name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        sudo apt-get install uuid-dev zlib1g-dev
        make INTEGRATION=1 DEBUG=0
    - name: verify
      run: |
        ./backup.e4
        ./restore.e4
        test/test 10M no
        test/test 1G yes
